USE ROLE BILLING

CREATE WAREHOUSE EG_HD_BILLING
WITH WAREHOUSE_SIZE = 'X-SMALL'
   MAX_CLUSTER_COUNT = 3
   MIN_CLUSTER_COUNT = 1
   AUTO_RESUME = TRUE
   AUTO_SUSPEND = 60
   INITIALLY_SUSPENDED = FALSE;

SHOW WAREHOUSES
use  WAREHOUSE EG_HD_BILLING
SHOW GRANTS ON SCHEMA PUBLIC TO ROLE BILLING


SHOW GRANTS TO ROLE BILLING;

SHOW GRANTS ON SCHEMA HEALTH_DB.PUBLIC;

USE DATABASE HEALTH_DB;
USE SCHEMA PUBLIC; -- Replace with the actual schema name

select * from  BILLING