use role doctor

USE ROLE 
CREATE WAREHOUSE EG_HD
WITH WAREHOUSE_SIZE = 'X-SMALL'
   MAX_CLUSTER_COUNT = 3
   MIN_CLUSTER_COUNT = 1
   AUTO_RESUME = TRUE
   AUTO_SUSPEND = 60
   INITIALLY_SUSPENDED = FALSE;

SHOW WAREHOUSES
use  WAREHOUSE EG_HD

USE DATABASE HEALTH_DB;
SHOW SCHEMAS;
SELECT CURRENT_ROLE();

SHOW GRANTS TO ROLE DOCTOR;

SHOW GRANTS ON SCHEMA HEALTH_DB.PUBLIC;


select * from MEDICAL_RECORDS 
select * from  LAB_RESULTS
select * from  PRESCRIPTIONS

-- in another tab
USE ROLE ACCOUNTADMIN
GRANT USAGE ON SCHEMA HEALTH_DB.PUBLIC TO ROLE DOCTOR;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTH_DB.PUBLIC TO ROLE DOCTOR;