USE ROLE NURSE

CREATE WAREHOUSE EG_HD_NURSE
WITH WAREHOUSE_SIZE = 'X-SMALL'
   MAX_CLUSTER_COUNT = 3
   MIN_CLUSTER_COUNT = 1
   AUTO_RESUME = TRUE
   AUTO_SUSPEND = 60
   INITIALLY_SUSPENDED = FALSE;

SHOW WAREHOUSES
use  WAREHOUSE EG_HD_NURSE
SHOW GRANTS ON SCHMEA PUBLIC TO ROLE NURSE


SHOW GRANTS TO ROLE NURSE;

SHOW GRANTS ON SCHEMA HEALTH_DB.PUBLIC;

USE DATABASE HEALTH_DB;
USE SCHEMA PUBLIC; -- Replace with the actual schema name

select * from  LAB_RESULTS
select * from  PATIENTS